name = "six-five-apps-my-people"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "six-five-apps-my-people"
database_id = "7b7792dd-6498-494a-9a2a-b337c636e663"
